using System;
using System.Threading.Tasks;

namespace BlazorWasm.MiniPOS.Services
{
    public class DataSeederService
    {
        private readonly IDbService _dbService;

        public DataSeederService(IDbService dbService)
        {
            _dbService = dbService;
        }

        public async Task SeedIfEmptyAsync()
        {
            try
            {
                // Check if we have any voucher heads (sales transactions)
                var voucherHeads = await _dbService.GetSaleVoucherHead();
                
                if (voucherHeads == null || voucherHeads.Count == 0)
                {
                    // If no sales data, check if we have products (they might be auto-generated by AppDbService)
                    var products = await _dbService.GetProductList();
                    
                    if (products != null && products.Count > 0)
                    {
                        // Generate data for the last 30 days
                        var start = DateTime.Now.AddDays(-30);
                        var end = DateTime.Now;
                        
                        // We use a dummy progress reporter
                        var progress = new Progress<double>();
                        
                        await _dbService.GenerateDataAsync(start, end, progress);
                    }
                }
            }
            catch (Exception ex)
            {
                // Silently fail to not block app startup if something goes wrong with seeding
                Console.WriteLine($"Auto-seeding failed: {ex.Message}");
            }
        }
    }
}
